use_frameworks!

target 'LYSGoogleAd_Example' do
#  pod 'LYSGoogleAd', :path => '../'

    pod 'Google-Mobile-Ads-SDK'
     pod 'Masonry'

  target 'LYSGoogleAd_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
  end
end
