use_frameworks!

target 'LYSGoogleAd_Example' do
#  pod 'LYSGoogleAd', :path => '../'

    pod 'Google-Mobile-Ads-SDK', '~> 7.18.0'
     pod 'Masonry', '~> 1.0.2'

  target 'LYSGoogleAd_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
